service: voxel-middynet-httpCorsSample

provider:
  name: aws
  runtime: dotnetcore3.1
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultRegion: eu-west-1
  defaultStage: dev${env:SLSUSER, ""}
  sqsTracingSampleQueueName: ${self:service}-${self:provider.stage}-httpCorsSample
package:
  individually: true

functions:
  httpCorsSample:
    handler: Voxel.MiddyNet.HttpCorsSample::Voxel.MiddyNet.HttpCorsSample.HttpCorsHeaders::Handler
    package:
      artifact: bin/Release/netcoreapp3.1/Voxel.MiddyNet.HttpCorsSample.zip
    events:
      - http: GET testHttp
